// Code generated by ent, DO NOT EDIT.

package rank

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the rank type in the database.
	Label = "rank"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldNext holds the string denoting the next field in the database.
	FieldNext = "next"
	// Table holds the table name of the rank in the database.
	Table = "ranks"
)

// Columns holds all SQL columns for rank fields.
var Columns = []string{
	FieldID,
	FieldNext,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultNext holds the default value on creation for the "next" field.
	DefaultNext string
)

// OrderOption defines the ordering options for the Rank queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByNext orders the results by the next field.
func ByNext(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNext, opts...).ToFunc()
}
