// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// RanksColumns holds the columns for the "ranks" table.
	RanksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "next", Type: field.TypeString, Default: "0|AA"},
	}
	// RanksTable holds the schema information for the "ranks" table.
	RanksTable = &schema.Table{
		Name:       "ranks",
		Columns:    RanksColumns,
		PrimaryKey: []*schema.Column{RanksColumns[0]},
	}
	// ShowsColumns holds the columns for the "shows" table.
	ShowsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "order", Type: field.TypeString},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"movie", "tv"}},
		{Name: "added_date", Type: field.TypeTime},
	}
	// ShowsTable holds the schema information for the "shows" table.
	ShowsTable = &schema.Table{
		Name:       "shows",
		Columns:    ShowsColumns,
		PrimaryKey: []*schema.Column{ShowsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		RanksTable,
		ShowsTable,
	}
)

func init() {
}
