// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/BlindGarret/movie-queue/ent/predicate"
	"github.com/BlindGarret/movie-queue/ent/rank"
)

// RankUpdate is the builder for updating Rank entities.
type RankUpdate struct {
	config
	hooks    []Hook
	mutation *RankMutation
}

// Where appends a list predicates to the RankUpdate builder.
func (ru *RankUpdate) Where(ps ...predicate.Rank) *RankUpdate {
	ru.mutation.Where(ps...)
	return ru
}

// SetNext sets the "next" field.
func (ru *RankUpdate) SetNext(s string) *RankUpdate {
	ru.mutation.SetNext(s)
	return ru
}

// SetNillableNext sets the "next" field if the given value is not nil.
func (ru *RankUpdate) SetNillableNext(s *string) *RankUpdate {
	if s != nil {
		ru.SetNext(*s)
	}
	return ru
}

// Mutation returns the RankMutation object of the builder.
func (ru *RankUpdate) Mutation() *RankMutation {
	return ru.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ru *RankUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, ru.sqlSave, ru.mutation, ru.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ru *RankUpdate) SaveX(ctx context.Context) int {
	affected, err := ru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ru *RankUpdate) Exec(ctx context.Context) error {
	_, err := ru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ru *RankUpdate) ExecX(ctx context.Context) {
	if err := ru.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ru *RankUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(rank.Table, rank.Columns, sqlgraph.NewFieldSpec(rank.FieldID, field.TypeInt))
	if ps := ru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ru.mutation.Next(); ok {
		_spec.SetField(rank.FieldNext, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rank.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ru.mutation.done = true
	return n, nil
}

// RankUpdateOne is the builder for updating a single Rank entity.
type RankUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RankMutation
}

// SetNext sets the "next" field.
func (ruo *RankUpdateOne) SetNext(s string) *RankUpdateOne {
	ruo.mutation.SetNext(s)
	return ruo
}

// SetNillableNext sets the "next" field if the given value is not nil.
func (ruo *RankUpdateOne) SetNillableNext(s *string) *RankUpdateOne {
	if s != nil {
		ruo.SetNext(*s)
	}
	return ruo
}

// Mutation returns the RankMutation object of the builder.
func (ruo *RankUpdateOne) Mutation() *RankMutation {
	return ruo.mutation
}

// Where appends a list predicates to the RankUpdate builder.
func (ruo *RankUpdateOne) Where(ps ...predicate.Rank) *RankUpdateOne {
	ruo.mutation.Where(ps...)
	return ruo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ruo *RankUpdateOne) Select(field string, fields ...string) *RankUpdateOne {
	ruo.fields = append([]string{field}, fields...)
	return ruo
}

// Save executes the query and returns the updated Rank entity.
func (ruo *RankUpdateOne) Save(ctx context.Context) (*Rank, error) {
	return withHooks(ctx, ruo.sqlSave, ruo.mutation, ruo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ruo *RankUpdateOne) SaveX(ctx context.Context) *Rank {
	node, err := ruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ruo *RankUpdateOne) Exec(ctx context.Context) error {
	_, err := ruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ruo *RankUpdateOne) ExecX(ctx context.Context) {
	if err := ruo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ruo *RankUpdateOne) sqlSave(ctx context.Context) (_node *Rank, err error) {
	_spec := sqlgraph.NewUpdateSpec(rank.Table, rank.Columns, sqlgraph.NewFieldSpec(rank.FieldID, field.TypeInt))
	id, ok := ruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Rank.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, rank.FieldID)
		for _, f := range fields {
			if !rank.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != rank.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ruo.mutation.Next(); ok {
		_spec.SetField(rank.FieldNext, field.TypeString, value)
	}
	_node = &Rank{config: ruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rank.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ruo.mutation.done = true
	return _node, nil
}
