// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/BlindGarret/movie-queue/ent/rank"
	"github.com/BlindGarret/movie-queue/ent/schema"
	"github.com/BlindGarret/movie-queue/ent/show"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	rankFields := schema.Rank{}.Fields()
	_ = rankFields
	// rankDescNext is the schema descriptor for next field.
	rankDescNext := rankFields[0].Descriptor()
	// rank.DefaultNext holds the default value on creation for the next field.
	rank.DefaultNext = rankDescNext.Default.(string)
	showFields := schema.Show{}.Fields()
	_ = showFields
	// showDescAddedDate is the schema descriptor for addedDate field.
	showDescAddedDate := showFields[3].Descriptor()
	// show.DefaultAddedDate holds the default value on creation for the addedDate field.
	show.DefaultAddedDate = showDescAddedDate.Default.(func() time.Time)
}
