// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/BlindGarret/movie-queue/ent/show"
)

// Show is the model entity for the Show schema.
type Show struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Order holds the value of the "order" field.
	Order string `json:"order,omitempty"`
	// Type holds the value of the "type" field.
	Type show.Type `json:"type,omitempty"`
	// AddedDate holds the value of the "addedDate" field.
	AddedDate    time.Time `json:"addedDate,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Show) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case show.FieldID:
			values[i] = new(sql.NullInt64)
		case show.FieldName, show.FieldOrder, show.FieldType:
			values[i] = new(sql.NullString)
		case show.FieldAddedDate:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Show fields.
func (s *Show) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case show.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			s.ID = int(value.Int64)
		case show.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				s.Name = value.String
			}
		case show.FieldOrder:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field order", values[i])
			} else if value.Valid {
				s.Order = value.String
			}
		case show.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				s.Type = show.Type(value.String)
			}
		case show.FieldAddedDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field addedDate", values[i])
			} else if value.Valid {
				s.AddedDate = value.Time
			}
		default:
			s.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Show.
// This includes values selected through modifiers, order, etc.
func (s *Show) Value(name string) (ent.Value, error) {
	return s.selectValues.Get(name)
}

// Update returns a builder for updating this Show.
// Note that you need to call Show.Unwrap() before calling this method if this Show
// was returned from a transaction, and the transaction was committed or rolled back.
func (s *Show) Update() *ShowUpdateOne {
	return NewShowClient(s.config).UpdateOne(s)
}

// Unwrap unwraps the Show entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (s *Show) Unwrap() *Show {
	_tx, ok := s.config.driver.(*txDriver)
	if !ok {
		panic("ent: Show is not a transactional entity")
	}
	s.config.driver = _tx.drv
	return s
}

// String implements the fmt.Stringer.
func (s *Show) String() string {
	var builder strings.Builder
	builder.WriteString("Show(")
	builder.WriteString(fmt.Sprintf("id=%v, ", s.ID))
	builder.WriteString("name=")
	builder.WriteString(s.Name)
	builder.WriteString(", ")
	builder.WriteString("order=")
	builder.WriteString(s.Order)
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", s.Type))
	builder.WriteString(", ")
	builder.WriteString("addedDate=")
	builder.WriteString(s.AddedDate.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Shows is a parsable slice of Show.
type Shows []*Show
