// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Rank is the predicate function for rank builders.
type Rank func(*sql.Selector)

// Show is the predicate function for show builders.
type Show func(*sql.Selector)
